# Intro to Recommender Systems Lab

Complete the exercises below to solidify your knowledge and understanding of recommender systems.

For this lab, we are going to be putting together a user similarity based recommender system in a step-by-step fashion. Our data set contains customer grocery purchases, and we will use similar purchase behavior to inform our recommender system. Our recommender system will generate 5 recommendations for each customer based on the purchases they have made.

In [4]:
import pandas as pd
from scipy.spatial.distance import pdist, squareform

In [5]:
data = pd.read_csv('../data/customer_product_sales.csv')

In [6]:
data.head()

,CustomerID,FirstName,LastName,SalesID,ProductID,ProductName,Quantity
0,61288,Rosa,Andersen,134196,229,Bread - Hot Dog Buns,16
1,77352,Myron,Murray,6167892,229,Bread - Hot Dog Buns,20
2,40094,Susan,Stevenson,5970885,229,Bread - Hot Dog Buns,11
3,23548,Tricia,Vincent,6426954,229,Bread - Hot Dog Buns,6
4,78981,Scott,Burch,819094,229,Bread - Hot Dog Buns,20

In [4]:
len(data)

68584

## Step 1: Create a data frame that contains the total quantity of each product purchased by each customer.

You will need to group by CustomerID and ProductName and then sum the Quantity field.

In [7]:
# Agrupamos por customerID y ProductName que se repitan y sumamos las cantidades.

data_customer_totals = data.groupby(['CustomerID', 'ProductName'])['Quantity'].sum().reset_index()

In [8]:
data_customer_totals

       CustomerID                    ProductName  Quantity
0              33               Apricots - Dried         1
1              33              Assorted Desserts         1
2              33        Bandage - Flexible Neon         1
3              33  Bar Mix - Pina Colada, 355 Ml         1
4              33         Beans - Kidney, Canned         1
...           ...                            ...       ...
63623       98200                   Vol Au Vents        50
63624       98200                  Wasabi Powder        25
63625       98200       Wine - Fume Blanc Fetzer        25
63626       98200  Wine - Hardys Bankside Shiraz        25
63627       98200        Yogurt - French Vanilla        25

[63628 rows x 3 columns]

## Step 2: Use the `pivot_table` method to create a product by customer matrix.

The rows of the matrix should represent the products, the columns should represent the customers, and the values should be the quantities of each product purchased by each customer. You will also need to replace nulls with zeros, which you can do using the `fillna` method.

In [9]:
pd.pivot_table(data_customer_totals, values='Quantity', index='ProductName', columns='CustomerID', fill_value= 0)

CustomerID,33,200,264,356,412,464,477,639,649,669,...,97697,97753,97769,97793,97900,97928,98069,98159,98185,98200
ProductName,,,,,,,,,,,,,,,,,,,,,
Anchovy Paste - 56 G Tube,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Appetizer - Mini Egg Roll, Shrimp",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,25.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Appetizer - Mushroom Tart,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0
Appetizer - Sausage Rolls,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,25.0,25.0,25.0,0.0,25.0,0.0
Apricots - Dried,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yeast Dry - Fermipan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0
Yoghurt Tubes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0,0.0
"Yogurt - Blueberry, 175 Gr",0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,25.0,0.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0
Yogurt - French Vanilla,1.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,1.0,...,0.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0
Zucchini - Yellow,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
product_customer_matrix = data_customer_totals.pivot_table(index='ProductName', columns='CustomerID', values='Quantity', fill_value=0)

product_customer_matrix

CustomerID,33,200,264,356,412,464,477,639,649,669,...,97697,97753,97769,97793,97900,97928,98069,98159,98185,98200
ProductName,,,,,,,,,,,,,,,,,,,,,
Anchovy Paste - 56 G Tube,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Appetizer - Mini Egg Roll, Shrimp",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,25.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Appetizer - Mushroom Tart,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0
Appetizer - Sausage Rolls,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,25.0,25.0,25.0,0.0,25.0,0.0
Apricots - Dried,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yeast Dry - Fermipan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0
Yoghurt Tubes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0,0.0
"Yogurt - Blueberry, 175 Gr",0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,25.0,0.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0
Yogurt - French Vanilla,1.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,1.0,...,0.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0
Zucchini - Yellow,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Step 3: Create a customer similarity matrix using `squareform` and `pdist`. For the distance metric, choose "euclidean."

In [11]:
# Calcular las distancias euclidianas entre clientes

customer_distances = pdist(product_customer_matrix.T, metric='euclidean')

In [12]:
# Convertir las distancias en una matriz cuadrada
customer_similarity_matrix = pd.DataFrame(squareform(customer_distances), 
                                           index=product_customer_matrix.columns, 
                                           columns=product_customer_matrix.columns)

In [13]:
customer_similarity_matrix

CustomerID,33,200,264,356,412,464,477,639,649,669,...,97697,97753,97769,97793,97900,97928,98069,98159,98185,98200
CustomerID,,,,,,,,,,,,,,,,,,,,,
33,0.000000,11.916375,10.488088,11.224972,11.401754,11.090537,12.409674,11.045361,11.269428,11.489125,...,206.871941,213.180675,225.656819,198.232187,230.913404,220.501701,217.188858,228.628520,239.000000,229.773802
200,11.916375,0.000000,11.747340,12.083046,12.569805,12.288206,12.165525,12.083046,11.874342,12.000000,...,206.310446,212.635839,224.697575,197.139544,230.952376,220.202180,215.728997,228.010965,239.037654,229.704158
264,10.488088,11.747340,0.000000,11.489125,11.224972,11.445523,12.000000,11.401754,11.180340,11.747340,...,206.387984,212.946003,225.435135,197.600607,230.371439,219.136943,216.612557,228.081126,238.266657,229.773802
356,11.224972,12.083046,11.489125,0.000000,12.083046,11.789826,12.328828,11.135529,11.958261,12.165525,...,206.649462,213.082144,225.452878,197.494304,231.038958,219.952268,217.437347,228.098663,238.493186,229.464594
412,11.401754,12.569805,11.224972,12.083046,0.000000,11.704700,12.328828,11.135529,11.789826,11.747340,...,206.900942,211.679002,225.572605,197.630969,230.614397,219.733930,217.446545,227.997807,238.396728,228.927936
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97928,220.501701,220.202180,219.136943,219.952268,219.733930,219.599636,219.538152,219.924987,219.827205,220.070443,...,283.945417,283.945417,302.076149,272.717803,278.388218,0.000000,273.861279,291.547595,306.186218,307.205143
98069,217.188858,215.728997,216.612557,217.437347,217.446545,217.425849,216.903204,217.294731,217.080630,216.751009,...,283.945417,283.945417,295.803989,283.945417,285.043856,273.861279,0.000000,287.228132,297.909382,294.745653
98159,228.628520,228.010965,228.081126,228.098663,227.997807,228.197283,228.028507,228.181945,227.868383,228.103047,...,283.945417,279.508497,300.000000,290.473751,300.000000,291.547595,287.228132,0.000000,304.138127,305.163890
98185,239.000000,239.037654,238.266657,238.493186,238.396728,239.006276,238.949786,238.468027,238.692271,239.334494,...,301.039864,315.238005,306.186218,292.617498,314.245127,306.186218,297.909382,304.138127,0.000000,303.108891
98200,229.773802,229.704158,229.773802,229.464594,228.927936,229.017467,229.503813,229.656265,229.997826,229.032749,...,291.547595,297.909382,294.745653,289.395923,303.108891,307.205143,294.745653,305.163890,303.108891,0.000000

## Step 4: Check your results by generating a list of the top 5 most similar customers for a specific CustomerID.

In [12]:
# Similarities to the new User

customer_similarity_matrix = customer_similarity_matrix[356].sort_values(ascending=True)[1:]

customer_similarity_matrix.head(5)

CustomerID
3317    10.677078
1008    10.723805
3305    10.862780
3253    10.862780
2617    11.000000
Name: 356, dtype: float64

In [15]:
# Especificar el CustomerID para el que deseas encontrar los clientes similares
target_customer_id = 200

# Obtener las similitudes del cliente objetivo con todos los demÃ¡s clientes
similarities_with_target_customer = customer_similarity_matrix[target_customer_id].sort_values(ascending=False)

# Excluir el propio cliente objetivo de la lista de clientes similares
top_similar_customers = similarities_with_target_customer.drop(target_customer_id).head(5)

In [16]:
# Mostrar la lista de los 5 clientes mÃ¡s similares
print("Top 5 clientes mÃ¡s similares para {}: \n{}".format(target_customer_id, top_similar_customers))

Top 5 clientes mÃ¡s similares para 200:
CustomerID
92255    248.050398
97324    246.452835
95017    243.903670
92492    240.185345
91777    239.284350
Name: 200, dtype: float64

## Step 5: From the data frame you created in Step 1, select the records for the list of similar CustomerIDs you obtained in Step 4.

In [18]:
 # Obtener los CustomerIDs de los clientes similares obtenidos en el Paso 4
similar_customer_ids = top_similar_customers.index.tolist()

# Seleccionar los registros para los CustomerIDs similares
similar_customer_records = data_customer_totals[data_customer_totals['CustomerID'].isin(similar_customer_ids)]

similar_customer_records.head()

       CustomerID                        ProductName  Quantity
59478       91777  Appetizer - Mini Egg Roll, Shrimp        24
59479       91777                    Banana - Leaves        24
59480       91777                     Banana Turning        24
59481       91777              Bandage - Fexible 1x3        24
59482       91777            Bandage - Flexible Neon        24

## Step 6: Aggregate those customer purchase records by ProductName, sum the Quantity field, and then rank them in descending order by quantity.

This will give you the total number of each product purchased by the 5 most similar customers to the customer you selected in order from most purchased to least.

In [21]:
# Agregar los registros de compra de los 5 clientes mÃ¡s similares por ProductName y sumar las cantidades
top_5_similar_customers_purchase_agg = top_5_similar_customer_records.groupby('ProductName')['Quantity'].sum().reset_index()

# Clasificar los productos en orden descendente segÃºn la cantidad total comprada
top_5_similar_customers_purchase_agg_sorted = top_5_similar_customers_purchase_agg.sort_values(by='Quantity', ascending=False)

top_5_similar_customers_purchase_agg_sorted.head()

                          ProductName  Quantity
21      Beef - Tenderlion, Center Cut       122
227           Turnip - White, Organic       122
209               Squid U5 - Thailand       121
134  Muffin Chocolate Individual Wrap        98
159       Pastry - Butterscotch Baked        98

## Step 7: Filter the list for products that the chosen customer has not yet purchased and then recommend the top 5 products with the highest quantities that are left.

- Merge the ranked products data frame with the customer product matrix on the ProductName field.
- Filter for records where the chosen customer has not purchased the product.
- Show the top 5 results.

In [24]:
# Obtener los registros de compra del cliente seleccionado
selected_customer_records = data_customer_totals[data_customer_totals['CustomerID'] == target_customer_id]

# Obtener los ProductName que el cliente seleccionado ya ha comprado
products_purchased_by_selected_customer = selected_customer_records['ProductName'].tolist()

# Filtrar los productos recomendados para aquellos que el cliente seleccionado aÃºn no ha comprado
recommended_products = top_5_similar_customers_purchase_agg_sorted[~top_5_similar_customers_purchase_agg_sorted['ProductName'].isin(products_purchased_by_selected_customer)]

recommended_products.head(5)

                          ProductName  Quantity
21      Beef - Tenderlion, Center Cut       122
134  Muffin Chocolate Individual Wrap        98
159       Pastry - Butterscotch Baked        98
63                        Clam Nectar        98
150                      Onion Powder        98

## Step 8: Now that we have generated product recommendations for a single user, put the pieces together and iterate over a list of all CustomerIDs.

- Create an empty dictionary that will hold the recommendations for all customers.
- Create a list of unique CustomerIDs to iterate over.
- Iterate over the customer list performing steps 4 through 7 for each and appending the results of each iteration to the dictionary you created.

In [25]:
# Crear un diccionario vacÃ­o para almacenar las recomendaciones para todos los clientes
recommendations_dict = {}

# Obtener una lista de CustomerIDs Ãºnicos
unique_customer_ids = data_customer_totals['CustomerID'].unique()

# Iterar sobre la lista de CustomerIDs
for customer_id in unique_customer_ids:
    # Step 4: Obtener los 5 clientes mÃ¡s similares al cliente actual
    similarities_with_customer = customer_similarity_matrix[customer_id].sort_values(ascending=False)
    top_5_similar_customers = similarities_with_customer.drop(customer_id).head(5)
    
    # Step 6: Agregar los registros de compra de los 5 clientes mÃ¡s similares por ProductName, sumar las cantidades y clasificar los productos
    similar_customer_ids = top_5_similar_customers.index.tolist()
    similar_customer_records = data_customer_totals[data_customer_totals['CustomerID'].isin(similar_customer_ids)]
    similar_customers_purchase_agg = similar_customer_records.groupby('ProductName')['Quantity'].sum().reset_index()
    similar_customers_purchase_agg_sorted = similar_customers_purchase_agg.sort_values(by='Quantity', ascending=False)
    
    # Step 7: Filtrar y recomendar los productos que el cliente actual no ha comprado aÃºn
    selected_customer_records = data_customer_totals[data_customer_totals['CustomerID'] == customer_id]
    products_purchased_by_selected_customer = selected_customer_records['ProductName'].tolist()
    recommended_products = similar_customers_purchase_agg_sorted[~similar_customers_purchase_agg_sorted['ProductName'].isin(products_purchased_by_selected_customer)].head(5)
    
    # Almacenar las recomendaciones en el diccionario
    recommendations_dict[customer_id] = recommended_products

# Mostrar las recomendaciones para un cliente especÃ­fico
sample_customer_id = unique_customer_ids[0]
print("Recomendaciones para el cliente {}: \n{}".format(sample_customer_id, recommendations_dict[sample_customer_id]))

Recomendaciones para el cliente 33:
                          ProductName  Quantity
21      Beef - Tenderlion, Center Cut       122
227           Turnip - White, Organic       122
209               Squid U5 - Thailand       121
134  Muffin Chocolate Individual Wrap        98
159       Pastry - Butterscotch Baked        98

##  Step 9: Store the results in a Pandas data frame. The data frame should a column for Customer ID and then a column for each of the 5 product recommendations for each customer.

In [44]:

# Iterar sobre la lista de CustomerIDs
for customer_id in unique_customer_ids_correlation:
    # Obtener los 5 clientes mÃ¡s similares al cliente actual usando la nueva matriz de similitud de correlaciÃ³n
    similarities_with_customer_correlation = customer_similarity_matrix_correlation[customer_id].sort_values()
    top_5_similar_customers_correlation = similarities_with_customer_correlation.drop(customer_id).head(5)
    
    # Agregar los registros de compra de los 5 clientes mÃ¡s similares por ProductName, sumar las cantidades y clasificar los productos
    similar_customer_ids_correlation = top_5_similar_customers_correlation.index.tolist()
    similar_customer_records_correlation = data_customer_totals[data_customer_totals['CustomerID'].isin(similar_customer_ids_correlation)]
    similar_customers_purchase_agg_correlation = similar_customer_records_correlation.groupby('ProductName')['Quantity'].sum().reset_index()
    similar_customers_purchase_agg_sorted_correlation = similar_customers_purchase_agg_correlation.sort_values(by='Quantity', ascending=False)
    
    # Filtrar y recomendar los productos que el cliente actual no ha comprado aÃºn
    selected_customer_records_correlation = data_customer_totals[data_customer_totals['CustomerID'] == customer_id]
    products_purchased_by_selected_customer_correlation = selected_customer_records_correlation['ProductName'].tolist()
    recommended_products_correlation = similar_customers_purchase_agg_sorted_correlation[~similar_customers_purchase_agg_sorted_correlation['ProductName'].isin(products_purchased_by_selected_customer_correlation)].head(5)
    
    # Almacenar las recomendaciones en el diccionario
    recommendations_dict_correlation[customer_id] = recommended_products_correlation['ProductName'].values.tolist()

# Convertir el diccionario de recomendaciones en un DataFrame de pandas
recommendations_df_correlation = pd.DataFrame.from_dict(recommendations_dict_correlation, orient='index')

# Resetear el Ã­ndice para que CustomerID sea una columna en lugar de un Ã­ndice
recommendations_df_correlation.reset_index(inplace=True)
recommendations_df_correlation.rename(columns={'index': 'CustomerID'}, inplace=True)

# Renombrar las columnas de las recomendaciones
recommendations_df_correlation.columns = ['CustomerID'] + [f'Recommendation_{i+1}' for i in range(5)]

# Mostrar el DataFrame de resultados
recommendations_df_correlation.head()

,CustomerID,Recommendation_1,Recommendation_2,Recommendation_3,Recommendation_4,Recommendation_5
0,33,Knife Plastic - White,Muffin - Zero Transfat,Banana Turning,Crush - Cream Soda,Veal - Osso Bucco
1,200,Otomegusa Dashi Konbu,Milk Powder,Potatoes - Idaho 100 Count,Crackers - Trio,Pail With Metal Handle 16l White
2,264,"Water - Mineral, Natural",Wine - Toasted Head,Snapple - Iced Tea Peach,Pickerel - Fillets,Garbag Bags - Black
3,356,Cheese - Taleggio D.o.p.,"Coconut - Shredded, Sweet",Cheese - Cheddarsliced,Ocean Spray - Kiwi Strawberry,Olives - Kalamata
4,412,Cake - Mini Cheesecake,Butter - Unsalted,"Salmon - Atlantic, Skin On",Wine - Hardys Bankside Shiraz,Gloves - Goldtouch Disposable

## Step 10: Change the distance metric used in Step 3 to something other than euclidean (correlation, cityblock, consine, jaccard, etc.). Regenerate the recommendations for all customers and note the differences.

In [37]:
# Calcular las distancias euclidianas entre clientes

customer_distances = pdist(product_customer_matrix.T, metric='cityblock')

# Convertir las distancias en una matriz cuadrada
customer_similarity_cityblock = pd.DataFrame(squareform(customer_distances), 
                                           index=product_customer_matrix.columns, 
                                           columns=product_customer_matrix.columns)

In [38]:
customer_similarity_cityblock

CustomerID,33,200,264,356,412,464,477,639,649,669,...,97697,97753,97769,97793,97900,97928,98069,98159,98185,98200
CustomerID,,,,,,,,,,,,,,,,,,,,,
33,0.0,124.0,100.0,108.0,118.0,111.0,128.0,112.0,115.0,114.0,...,1772.0,1678.0,1797.0,1482.0,1845.0,1755.0,1797.0,1803.0,2099.0,1872.0
200,124.0,0.0,122.0,126.0,142.0,131.0,128.0,128.0,123.0,122.0,...,1776.0,1684.0,1795.0,1480.0,1857.0,1763.0,1791.0,1807.0,2111.0,1884.0
264,100.0,122.0,0.0,116.0,112.0,117.0,126.0,118.0,115.0,120.0,...,1766.0,1676.0,1799.0,1474.0,1841.0,1735.0,1789.0,1795.0,2085.0,1874.0
356,108.0,126.0,116.0,0.0,124.0,121.0,128.0,108.0,123.0,122.0,...,1772.0,1680.0,1799.0,1478.0,1851.0,1749.0,1807.0,1797.0,2091.0,1872.0
412,118.0,142.0,112.0,124.0,0.0,123.0,128.0,112.0,125.0,120.0,...,1782.0,1668.0,1807.0,1482.0,1851.0,1753.0,1811.0,1801.0,2095.0,1866.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97928,1755.0,1763.0,1735.0,1749.0,1753.0,1744.0,1751.0,1743.0,1746.0,1751.0,...,2975.0,2775.0,3100.0,2625.0,2800.0,0.0,2750.0,2850.0,3350.0,3325.0
98069,1797.0,1791.0,1789.0,1807.0,1811.0,1804.0,1807.0,1797.0,1798.0,1797.0,...,3075.0,2975.0,3100.0,2925.0,2850.0,2750.0,0.0,2850.0,3250.0,3025.0
98159,1803.0,1807.0,1795.0,1797.0,1801.0,1798.0,1805.0,1795.0,1792.0,1799.0,...,3025.0,2725.0,3000.0,2875.0,3050.0,2850.0,2850.0,0.0,3150.0,3175.0
98185,2099.0,2111.0,2085.0,2091.0,2095.0,2098.0,2107.0,2085.0,2092.0,2107.0,...,3425.0,3525.0,3250.0,3025.0,3400.0,3350.0,3250.0,3150.0,0.0,3175.0
98200,1872.0,1884.0,1874.0,1872.0,1866.0,1863.0,1880.0,1868.0,1879.0,1866.0,...,3150.0,3100.0,3025.0,2950.0,3075.0,3325.0,3025.0,3175.0,3175.0,0.0